all:
	g++ -Wall -o testPoint testPoint.cpp Point.cpp
	g++ -Wall -o testShape testShape.cpp Shape.cpp Point.cpp
	g++ -Wall -o checkPack checkPack.cpp Domain.cpp Point.cpp Shape.cpp
	
clean:
	rm -f *.o testPoint testShape checkPack 